# tasks file for nfs_client
---
# This file defines the tasks for setting up NFS client

- name: Install NFS client package
  apt:
    name: nfs-common
    state: present
    update_cache: yes

- name: Create a mount point for the NFS share
  file:
    path: /home/ubuntu/dir-for-web/remote/data
    state: directory

- name: Mount the NFS shared directory for repositories
  mount:
    name: /home/ubuntu/dir-for-web/remote/data
    src: "{{ nfs_server_host }}:/home/ubuntu/repos"
    fstype: nfs
    state: mounted

- name: Ensure NFS mount persists after reboot
  mount:
    name: /home/ubuntu/dir-for-web/remote/data
    src: "{{ nfs_server_host }}:/home/ubuntu/repos"
    fstype: nfs
    opts: defaults
    state: present

