---
# tasks file for nfs_server_role

- name: Install NFS server package
  apt:
    name: nfs-kernel-server
    state: present
    update_cache: yes

- name: Create the shared directory for repositories
  file:
    path: /home/ubuntu/repos
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0777'

- name: Configure the exports file for the shared directory
  lineinfile:
    path: /etc/exports
    line: "/home/ubuntu/repos {{ item }}(rw,sync,no_subtree_check,all_squash,anonuid=1000,anongid=1000)"    #"/home/ubuntu/repos {{ item }}(rw,sync,no_subtree_check)"
    create: yes
  loop: "{{ gitea_host_names.values() }}"  # Dynamically loop over all host IPs in gitea_host_names

- name: Export the shared directory
  command: exportfs -a

- name: Restart NFS server
  service:
    name: nfs-kernel-server
    state: restarted
