---
# tasks file for nginx_role
- name: Install NGINX
  package:
    name: nginx
    state: present

- name: Remove default NGINX site configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Deploy custom nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - Reload NGINX
